### ISSUE TITLE
Release `reactivemongo-bson-compat` and other packages to 1.0.0

### ISSUE THREAD

**Issue by xBATx** [ReactiveMongo/ReactiveMongo-BSON#175]
Hi guys, 

I see that you released `reactivemongo` package to `1.0.0` but the latest version of `reactivemongo-bson-compat` is still `0.20.13`. Unfortunately, this cause some classpath issues. 

I would like to ask if you plan to support `reactivemongo-bson-compat` also with the future versions or it's by design - `0.20.13` the latest version?

Thanks in advance.

**Comment by cchantep** [comment]
Hi,

> This issue tracker is for confirmed issue/actionable feature request.
> 
> To ask question/for help, please use the [MailingList](https://groups.google.com/g/reactivemongo).

Anyway, `bson-compat` was there to provide compatibility between the former BSON package `reactivemongo.bson` and the [new `reactivemongo.api.bson`](http://reactivemongo.org/releases/1.0/documentation/bson/overview.html).
As the deprecated package no longer exists since the 1.0.0 release,  there is also no longer compatibility required.
